# coding: utf-8

"""
    PRISM NBAPI

    This is a PRISM NBAPI API Client module.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: contact@kulcloud.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.filter_inner_object import FilterInnerObject  # noqa: E501
from swagger_client.rest import ApiException


class TestFilterInnerObject(unittest.TestCase):
    """FilterInnerObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFilterInnerObject(self):
        """Test FilterInnerObject"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.filter_inner_object.FilterInnerObject()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
