# coding: utf-8

"""
    PRISM NBAPI

    This is a PRISM NBAPI API Client module.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: contact@kulcloud.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.rate_limit_merter_id import RateLimitMerterId  # noqa: E501
from swagger_client.rest import ApiException


class TestRateLimitMerterId(unittest.TestCase):
    """RateLimitMerterId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRateLimitMerterId(self):
        """Test RateLimitMerterId"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.rate_limit_merter_id.RateLimitMerterId()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
