# coding: utf-8

"""
    PRISM NBAPI

    This is a PRISM NBAPI API Client module.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: contact@kulcloud.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.ratelimit_api import RatelimitApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRatelimitApi(unittest.TestCase):
    """RatelimitApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.ratelimit_api.RatelimitApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_rate_limit(self):
        """Test case for create_rate_limit

        Create NPB Rate Limit  # noqa: E501
        """
        pass

    def test_delete_rate_limit(self):
        """Test case for delete_rate_limit

        Delete NPB Rate Limit  # noqa: E501
        """
        pass

    def test_get_all_rate_limit(self):
        """Test case for get_all_rate_limit

        Get NPB Rate Limit All  # noqa: E501
        """
        pass

    def test_get_rate_limit(self):
        """Test case for get_rate_limit

        Get NPB Rate Limit  # noqa: E501
        """
        pass

    def test_update_rate_limit(self):
        """Test case for update_rate_limit

        Update NPB Rate Limit  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
