# coding: utf-8

"""
    PRISM NBAPI

    This is a PRISM NBAPI API Client module.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: contact@kulcloud.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class RateLimitMerterId(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'mid': 'str',
        'dpid': 'str'
    }

    attribute_map = {
        'mid': 'mid',
        'dpid': 'dpid'
    }

    def __init__(self, mid=None, dpid=None):  # noqa: E501
        """RateLimitMerterId - a model defined in Swagger"""  # noqa: E501

        self._mid = None
        self._dpid = None
        self.discriminator = None

        if mid is not None:
            self.mid = mid
        if dpid is not None:
            self.dpid = dpid

    @property
    def mid(self):
        """Gets the mid of this RateLimitMerterId.  # noqa: E501


        :return: The mid of this RateLimitMerterId.  # noqa: E501
        :rtype: str
        """
        return self._mid

    @mid.setter
    def mid(self, mid):
        """Sets the mid of this RateLimitMerterId.


        :param mid: The mid of this RateLimitMerterId.  # noqa: E501
        :type: str
        """

        self._mid = mid

    @property
    def dpid(self):
        """Gets the dpid of this RateLimitMerterId.  # noqa: E501


        :return: The dpid of this RateLimitMerterId.  # noqa: E501
        :rtype: str
        """
        return self._dpid

    @dpid.setter
    def dpid(self, dpid):
        """Sets the dpid of this RateLimitMerterId.


        :param dpid: The dpid of this RateLimitMerterId.  # noqa: E501
        :type: str
        """

        self._dpid = dpid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RateLimitMerterId, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RateLimitMerterId):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
